site_name: CK AstroTools
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            show_submodules: true
markdown_extensions:
  - markdown_include.include:
      base_path: docs/
  #- admonition
nav:
  - Home: index.md
  - API: references.md